### ISSUE TITLE
extension registry naming and API

### ISSUE THREAD

**Issue by liggitt** [openshift/angular-extension-registry#20]
Maybe it's my eclipse roots showing... I like extensionPoint, extension, and extensionRegistry
- the extension-point is the point that can be extended
- the extension does the extending
- it gets registered into the extension registry

Directive example:

```
<extension-point name="sidebar" ...>
```

Extension registry example:

```
var myExtension = function(args) { return {type:'text',text:'Hello, world!'} };
var handle = extensionRegistry.add('sidebar', 'text', myExtension);
extensionRegistry.remove(handle);
```

Thoughts on the following tweaks:
- Make add/remove (or register/unregister, etc) both functions on the extension registry. The returned handle is opaque to the caller.
- Require type to be specified when registering, so filtering can be done before calling the extension (e.g. if the extension only returns links, and we're rendering text, don't call it)

**Comment by benjaminapetersen** [comment]
TODO list:
- [x] rename the directive `extension-point`
- [x] rename `extensionInput` to `extensionRegistry`
- [x] rework deregistration into:
  -  `extensionRegistry.deregister(handle)`   `.remove(handle)`  OR
  - `var handle = extensionRegistry.add( /../ )` and `extensionRegistry.remove( handle )`
  - this would replace the returned object with a `.deregister()` fn

**Comment by benjaminapetersen** [comment]
PR #32 takes care of first 2 items on this list.
