### ISSUE TITLE
Remove multi-type extension rendering

### ISSUE THREAD

**Issue by liggitt** [openshift/angular-extension-registry#21]
For the extension-output directive, what would it look like to render multiple types of output (e.g. two text outputs, then a link, then html, then text, then a link) simultaneously? Seems like I'd want to do one type at a time, especially since a single extension might return multiple representations of the same data (a text version and a link version), which would look silly rendered side-by-side.

For a particular view, I think we'd pick a single representation

**Comment by benjaminapetersen** [comment]
I'm good with that, when we use it was can just limit it down to a single type:

``` html
<div
  extension-output
  extension-name="sidebar"
  extension-types="link"
  extension-args="args"
  extension-limit="2"></div>                    
```

 And if we decide we want all links first, then all text after:

``` html
<div
  extension-output
  extension-name="sidebar"
  extension-types="link"
  extension-args="args"
  extension-limit="2"></div>                    
<div
  extension-output
  extension-name="sidebar"
  extension-types="text"
  extension-args="args"
  extension-limit="2"></div>                    

```
