### ISSUE TITLE
Extension output directive args vs options

### ISSUE THREAD

**Issue by liggitt** [openshift/angular-extension-registry#22]
For the extension-output directive, there are args that get passed to the extensions, but there are also options passed to the renderer/view, which are different per type (limit is only one. when rendering links, I could see rendering as a flat list, an action drop-down, etc.). probably worth thinking about what you'd call both of those things ("args" and "options"?), and how you'd accomodate different options for different types of output

**Comment by benjaminapetersen** [comment]
Currently I have `limit` as an attribute on the directive.  I'd probably suggest we add arguments for the directive as separate attributes, 1:1 ratio.

``` html
 <div
   extension-output
   extension-name="thing" 
   extension-types="text link"
   extension-args="friend"
   extension-limit="2"></div>
```

I'd like to be able to control row vs column layout w/css only.  Any other attrs that would be helpful for config?

**Comment by liggitt** [comment]
> Any other attrs that would be helpful for config?

Things like inline vs drop-down for link rendering.

side-question: how would you pass multiple args? extension-args="[foo,bar,baz]"? does that even work?

**Comment by benjaminapetersen** [comment]
I believe the angular way would be to make a single attribute for each configurable option.  if you passed something like that you'd have to build an object w/named properties in your controller & attach to scope.
