### ISSUE TITLE
Remove className from text and link types

### ISSUE THREAD

**Issue by liggitt** [openshift/angular-extension-registry#23]
For text and link types, we should try hard to make the extensions data-driven and leave rendering choices up to the output directive/view.

Letting them choose a className goes against that. Don't we want uniform appearance of the results of the extensions? I think className on link will cause problems if we want to render links inline or in a drop-down action menu

**Comment by benjaminapetersen** [comment]
Shall we pull @ajacobs21e to comment on this as well, re: design flexibility?

**Comment by liggitt** [comment]
I can't think of any uses of className that I like...
- custom appearance - don't want it, I want the extension point to control appearance
- external selection of the link element - don't want it, the extension point should control the DOM node
- any other cases?

**Comment by ajacobs21e** [comment]
How is className used?

**Comment by liggitt** [comment]
it adds to the "class" attribute on the link element... lets extenders apply custom styles to a particular link or find the DOM element via script

**Comment by ajacobs21e** [comment]
Unless there is a strong use case for extensions to have custom styles I would recommend against it.

**Comment by liggitt** [comment]
@benjaminapetersen we can always add it later if it becomes necessary. I'd rather address specific needs (icon, etc), with intent-driven fields in the structured data

**Comment by benjaminapetersen** [comment]
ok, cool.  we'll nix it.
