### ISSUE TITLE
Define behavior with promises

### ISSUE THREAD

**Issue by liggitt** [openshift/angular-extension-registry#25]
Should rendering happen immediately, and late-resolving promises pop things into view? Or should all values be resolved before anything is rendered?

**Comment by benjaminapetersen** [comment]
Currently the flow is more or less `$q.all( ).then( )`... so everything is resolved first, then rendering happens.  I tend to think we should keep it that way unless/until we find a case that shows this to be undesirable.  

The main issue will be when 1 or more promises fail and reject the whole set.  None of the items will render in this case.

**Comment by liggitt** [comment]
I'm ok with waiting for all to complete (resolve or fail). I'm not ok with one failing breaking all the others

**Comment by benjaminapetersen** [comment]
Yeah, that is more concerning to me as well. I'll look @ an adjustment.  I'm assuming there is an elegant way to handle this with `$q`.

**Comment by benjaminapetersen** [comment]
This is done, running the `/demo` w/browser simulating a 50kb/s throttle will show extensions rendering in view as promises resolve.  Extensions registering an error or returning an error will not affect other extensions.
