### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/angular-extension-registry#28]
Need a contributing section in README.md or a CONTRIBUTING.md file.

**Comment by benjaminapetersen** [comment]
Probably CONTRIBUTING.md is better, leave the README.md to usage.  Encourage style consistency, etc.

**Comment by wajeehsheikh** [comment]
I agree! Every open source project should have a separate CONTRIBUTING.MD file.
This provides a guideline for future contributors on how to raise issues and create a pull request .

I can get started on a solid template with some guide lines.
