### ISSUE TITLE
Improve the renderer template

### ISSUE THREAD

**Issue by benjaminapetersen** [openshift/angular-extension-registry#5]
The renderer template generates a few wrappers of markup that could be annoying to deal with.  It should be simple to style the output to be horizontal,vertical or whatever a user desires.

**Comment by benjaminapetersen** [comment]
IE, layout as row, column, whatever just with CSS.

**Comment by benjaminapetersen** [comment]
More specifically, the renderer perhaps should NOT add any markup.  Example:

``` html
<ul extension-point>
    <!-- existing markup is here... -->
    <li>foo</li>
    <li>bar</li>
    <!-- add new generated markup here, w/o destroying previous? -->
   <li>generated extension markup 1</li>
   <li>generated extension markup 2</li>
</ul>
```

Need to work out the details.  Configure the extension-point renderer directive, adjustable template?

**Comment by benjaminapetersen** [comment]
Some useful comments on [this SO article0(http://stackoverflow.com/questions/17090964/replace-element-in-angularjs-directive-linking-function).

In short, prob have to update the renderer to something like:

``` javascript
// replace is what completely replaces the original DOM node. 
// however, the renderer is an attribute on any node, such as a <ul> or <div>....
// UNLESS the renderer would instead be a child node of the parent, in above comment 
// a <li extension-point></li>, because this avoids some ugliness.
.directive('foo', function () {
    return {
        restrict: 'E',
        template: '<li ng-repeat="item in items">generated extension markup {{$index}}</li>',
        replace: true,
        scope: {
            items: "="
        }
    };
});
```

**Comment by benjaminapetersen** [comment]
On this, I think the final version should look like this:

``` html
<ul>
    <li>foo</li>
    <li>bar</li>    
    <li extension-point></li> <!-- extension point should generate 'x' <li> wrappers with content... -->
</ul>
```

With a subtle detail.  The `extension-point` attribute should be able to be placed on any DOM node, and that node (li, div, whatever) should be duplicated for each generated extension item.  The extension item should only be concerned with the contents of that node, no need to know the wrapper.  This way we have freedom to update our markup from `<li class="foo" extension-point>` to `<li class="foo bar-baz" extension-point>`.

**Comment by benjaminapetersen** [comment]
@jwforres @sg00dwin so I've been reading up on `replace: true` as a directive option, and it appears to be deprecated/discouraged due to causing a lot of issues (one example, [here](https://github.com/angular/angular.js/pull/10733)).  So I'm thinking of working towards minimizing w/o replace, probably would end up with something like this:

``` html
<ul>
    <li>foo</li>
    <li>bar</li>    
    <li extension-point>
        <!-- will have to generate a nested list :-/ -->
        <ul>
            <li>ext pt1</li>
            <li>ext pt2</li>
        </ul>
    </li>
</ul>
```

Not ideal, but I think we can work around a single nested `ul` tag & visually represent as if it is one list.  Thoughts?

**Comment by benjaminapetersen** [comment]
Fixed with PR #47

**Comment by jwforres** [comment]
somehow i completely missed this issue, so my concern is that we are working within the constraints of patternfly and bootstrap and we would have to potentially copy / overwrite a number of styles to make the dropdowns with nested `<ul>` elements behave. i can't say for sure though, did you try it to see what it looks like?

**Comment by benjaminapetersen** [comment]
I haven't pulled it into the web console yet, I think I've hit the major issues we wanted addressed & will now give that a swing.  I expect I'll need to open a follow-on.  

There are issues with using `ng-repeat`, `ng-include` and other directives on the same DOM node.  I can't eliminate all the wrapping, but was able to reduce significantly. We'll see how this approach works...
